export const actions = {
	NEW_ITEM: 'NEW_ITEM',
	DELETE_ITEM: 'DELETE_ITEM',
	LOAD_FROM_LOCALSTORAGE: 'LOAD_FROM_LOCALSTORAGE',
	EDIT_OPTIONS: 'EDIT_OPTIONS',
	ASK_FOR_REMOVE: 'ASK_FOR_REMOVE',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_LIST: 'RESET_LIST',
}
